/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Fish1.glb --transform --types 
Files: Fish1.glb [81.51KB] > /Users/normanqian/fractalcamp/gamesHackathon2/frontend/public/Fish1-transformed.glb [14.91KB] (82%)
*/

import * as THREE from "three";
import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";

type ActionName = "Armature|Swim";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    ClownFish_1: THREE.SkinnedMesh;
    ClownFish_2: THREE.SkinnedMesh;
    ClownFish_3: THREE.SkinnedMesh;
    Root: THREE.Bone;
  };
  materials: {
    Outline: THREE.MeshStandardMaterial;
    Body: THREE.MeshStandardMaterial;
    Stripes: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF("/Fish1-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes.Root} />
        </group>
        <group name="ClownFish" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="ClownFish_1"
            geometry={nodes.ClownFish_1.geometry}
            material={materials.Outline}
            skeleton={nodes.ClownFish_1.skeleton}
          />
          <skinnedMesh
            name="ClownFish_2"
            geometry={nodes.ClownFish_2.geometry}
            material={materials.Body}
            skeleton={nodes.ClownFish_2.skeleton}
          />
          <skinnedMesh
            name="ClownFish_3"
            geometry={nodes.ClownFish_3.geometry}
            material={materials.Stripes}
            skeleton={nodes.ClownFish_3.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Fish1-transformed.glb");
