/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Shark.glb --transform --types 
Files: Shark.glb [142.7KB] > /Users/normanqian/fractalcamp/gamesHackathon2/frontend/public/Shark-transformed.glb [50.98KB] (64%)
*/

import * as THREE from "three";
import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";

type ActionName =
  | "Fish_Armature|Attack"
  | "Fish_Armature|Death"
  | "Fish_Armature|Out_Of_Water"
  | "Fish_Armature|Swimming_Fast"
  | "Fish_Armature|Swimming_Impulse"
  | "Fish_Armature|Swimming_Normal";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Shark_1: THREE.SkinnedMesh;
    Shark_2: THREE.SkinnedMesh;
    Shark_3: THREE.SkinnedMesh;
    Shark_4: THREE.SkinnedMesh;
    Main1: THREE.Bone;
  };
  materials: {
    Shark_Dark: THREE.MeshStandardMaterial;
    Shark_Light: THREE.MeshStandardMaterial;
    Shark_Main: THREE.MeshStandardMaterial;
    Eyes: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF("/Shark-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="Fish_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes.Main1} />
        </group>
        <group name="Shark" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Shark_1"
            geometry={nodes.Shark_1.geometry}
            material={materials.Shark_Dark}
            skeleton={nodes.Shark_1.skeleton}
          />
          <skinnedMesh
            name="Shark_2"
            geometry={nodes.Shark_2.geometry}
            material={materials.Shark_Light}
            skeleton={nodes.Shark_2.skeleton}
          />
          <skinnedMesh
            name="Shark_3"
            geometry={nodes.Shark_3.geometry}
            material={materials.Shark_Main}
            skeleton={nodes.Shark_3.skeleton}
          />
          <skinnedMesh
            name="Shark_4"
            geometry={nodes.Shark_4.geometry}
            material={materials.Eyes}
            skeleton={nodes.Shark_4.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Shark-transformed.glb");
