/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Swordfish.glb --transform --types 
Files: Swordfish.glb [150.64KB] > /Users/normanqian/fractalcamp/gamesHackathon2/frontend/public/Swordfish-transformed.glb [50.15KB] (67%)
*/

import * as THREE from "three";
import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";

type ActionName =
  | "Fish_Armature|Attack"
  | "Fish_Armature|Death"
  | "Fish_Armature|Out_Of_Water"
  | "Fish_Armature|Swimming_Fast"
  | "Fish_Armature|Swimming_Impulse"
  | "Fish_Armature|Swimming_Normal";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Swordfish_1: THREE.SkinnedMesh;
    Swordfish_2: THREE.SkinnedMesh;
    Swordfish_3: THREE.SkinnedMesh;
    Swordfish_4: THREE.SkinnedMesh;
    Main1: THREE.Bone;
  };
  materials: {
    Swordfish_Light: THREE.MeshStandardMaterial;
    Swordfish_Main: THREE.MeshStandardMaterial;
    Swordfish_Dark: THREE.MeshStandardMaterial;
    Eyes: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF("/Swordfish-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="Fish_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <primitive object={nodes.Main1} />
        </group>
        <group name="Swordfish" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh
            name="Swordfish_1"
            geometry={nodes.Swordfish_1.geometry}
            material={materials.Swordfish_Light}
            skeleton={nodes.Swordfish_1.skeleton}
          />
          <skinnedMesh
            name="Swordfish_2"
            geometry={nodes.Swordfish_2.geometry}
            material={materials.Swordfish_Main}
            skeleton={nodes.Swordfish_2.skeleton}
          />
          <skinnedMesh
            name="Swordfish_3"
            geometry={nodes.Swordfish_3.geometry}
            material={materials.Swordfish_Dark}
            skeleton={nodes.Swordfish_3.skeleton}
          />
          <skinnedMesh
            name="Swordfish_4"
            geometry={nodes.Swordfish_4.geometry}
            material={materials.Eyes}
            skeleton={nodes.Swordfish_4.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Swordfish-transformed.glb");
